### ISSUE TITLE
Waste baskets with waste=trash;cigarettes don't show up

### ISSUE THREAD

**Issue by carstenhag** [InventivetalentDev/TrashApp#16]
++ Device Info ++
Manufacturer: OnePlus
Brand: OnePlus
Device: OnePlus5
Version API Level: 28
Version Release: 9

App Version Name: 0.5.2
App Version Code: 45000502
App Build Type: release
+++++++++++++

## What steps will reproduce the problem?
1. Open the map
2. Go to Heilbronn for example

## What were you expecting to happen? What happened instead?

Waste baskets with trash;cigarettes tagging get shown

Instead, they don't show up at all

**Comment by carstenhag** [comment]
If you look at taginfo you can tell I'm one of the few people tagging this combination. It makes sense though, because often the waste baskets have 2 slots.

**Comment by InventivetalentDev** [comment]
Could you elaborate a bit, please? What are you filtering by for it to now show up, or do they not appear in general?  

I'm guessing you're tagging stuff with `waste=trash;cigarettes`?

**Comment by carstenhag** [comment]
Exactly. I've attached a Screenshot of Heilbronn. Many waste baskets are missing. 

![Screenshot_20190910-205342](https://user-images.githubusercontent.com/3776997/64641766-22802e80-d40d-11e9-885d-947b1535919a.jpg)

**Comment by InventivetalentDev** [comment]
Alright, I'll look into that!

**Comment by InventivetalentDev** [comment]
Should show up in 0.5.4+ now.
